### ISSUE TITLE
Build error with dmd v2.073.0

### ISSUE THREAD

**Issue by pfusik** [epi/xebin#11]
C:\0\a8\xebin>dmd --version
    DMD32 D Compiler v2.073.0
    Copyright (c) 1999-2016 by Digital Mars written by Walter Bright

    C:\0\a8\xebin>make
    dub build -b release
    Performing "release" build using dmd for x86.
    xebin ~master: building configuration "application"...
    source\xebin\disasm.d(156,11): Deprecation: use std.algorithm.sort instead of .sort property
    source\xebin\disasm.d(170,5): Error: function xebin.disasm.instructionSplitter.Splitter.opApply (scope int delegate(ushort addr, AddrType atype, const(ubyte)[] bytes) dg) const is not callable using argument types (int delegate(ushort addr, AddrType atype, const(ubyte[]) bytes) @system)
    source\xebin\disasm.d(190,11): Deprecation: use std.algorithm.sort instead of .sort property
    dmd failed with exit code 1.
    make: *** [Makefile:11: all] Error 2

**Comment by epi** [comment]
Please use DMD 2.076 or newer.
