### ISSUE TITLE
feature request: support SAP files

### ISSUE THREAD

**Issue by pfusik** [epi/xebin#5]
I mostly miss listing binary headers and disassembly.

**Comment by pfusik** [comment]
> Want to have it done fast or well?

Fast, please.

**Comment by epi** [comment]
@pfusik check out branch 2.0. Most features are temporarily disabled but listing headers and disassembly should work for XEX and SAP files.

**Comment by epi** [comment]
"Co ma wisieć, nie nasiąknie za młodu."
